POST http://localhost:3001/api/noteAppUsers
Content-Type: application/json

{
    "username": "chewzzz",
    "name": "chewzzz",
    "password": "123456"
}


###

GET http://localhost:3001/api/noteAppUsers