GET https://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/639144999068ca3bdcc3fe02

###

PUT http://localhost:3001/api/notes/639144999068ca3bdcc3fe02
Content-Type: application/json
{
    "content": "yoyoyyo! PUT request is working!",
    "important": true
}