GET http://localhost:3001/api/blogs
Content-Type: application/json

###

GET http://localhost:3001/api/users
Content-Type: application/json

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoZXd6enoiLCJpZCI6IjYzYWJlODM3YWRmM2E4ZDNiZjIzYWIwMyIsImlhdCI6MTY3MjM2OTI0MiwiZXhwIjoxNjcyMzcyODQyfQ.wVyo9r4IawdmoymaRwxEct8JbV2VK228urbgCoB9xbw

{
    "title": "Introduction to JavaScript",
    "author": "J W Birch",
    "url": "google.com",
    "likes": 20
}

###


POST https://localhost:3001/api/login
Content-Type: application/json

{
    "username": "chewzzz",
    "password": "yoyoylolo"
}

###

DELETE http://localhost:3001/api/blogs/63abe837adf3a8d3bf23aafb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoZXd6enoiLCJpZCI6IjYzYWJlODM3YWRmM2E4ZDNiZjIzYWIwMyIsImlhdCI6MTY3MjM2OTI0MiwiZXhwIjoxNjcyMzcyODQyfQ.wVyo9r4IawdmoymaRwxEct8JbV2VK228urbgCoB9xbw

###