GET http://localhost:3001/api/blogs


###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ

{
    "name": "chewzzz",
    "number": "yoyoyyoyoyo"
}